# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9c173559a1130174a12a84d6d2cc4864807ab604472e4326273d4e90c9d0454d0d1c172e39ca1aadf3cfddafee4988012ea87d30e66771c22bfe0b3de11018c

test:
  secret_key_base: 47003c623ade960559b762bd8556c32d7ab4c158ea853d824787b83776e139d6654517f0225b74517e698c5f04495f63966e1abe59ba5d4686353dfe13b618e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
